// <auto-generated />
using System;
using GyakorlatiFeladat.DataContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GyakorlatiFeladat.DataContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250617154805_PasswordHash")]
    partial class PasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.FamilyUsers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("UserId");

                    b.ToTable("FamilyUsers");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.ShoppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("ShoppingItems");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.ShoppingItemVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShoppingItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingItemId");

                    b.ToTable("ShoppingItemVote");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskDesc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.FamilyUsers", b =>
                {
                    b.HasOne("GyakorlatiFeladat.DataContext.Entities.Family", "Family")
                        .WithMany("FamilyUsers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GyakorlatiFeladat.DataContext.Entities.User", "User")
                        .WithMany("FamilyUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.ShoppingItem", b =>
                {
                    b.HasOne("GyakorlatiFeladat.DataContext.Entities.Family", "Family")
                        .WithMany("ShoppingItems")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.ShoppingItemVote", b =>
                {
                    b.HasOne("GyakorlatiFeladat.DataContext.Entities.ShoppingItem", null)
                        .WithMany("Votes")
                        .HasForeignKey("ShoppingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.TaskItem", b =>
                {
                    b.HasOne("GyakorlatiFeladat.DataContext.Entities.Family", "Family")
                        .WithMany("TaskItems")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.User", b =>
                {
                    b.HasOne("GyakorlatiFeladat.DataContext.Entities.TaskItem", null)
                        .WithMany("Users")
                        .HasForeignKey("TaskItemId");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.Family", b =>
                {
                    b.Navigation("FamilyUsers");

                    b.Navigation("ShoppingItems");

                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.ShoppingItem", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.TaskItem", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GyakorlatiFeladat.DataContext.Entities.User", b =>
                {
                    b.Navigation("FamilyUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
